-- タグ本体
CREATE TABLE tags (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR(64) NOT NULL
);
-- 小文字で一意（アプリ側で小文字に寄せる前提でも、とりあえずユニーク）
CREATE UNIQUE INDEX uq_tags_name ON tags(name);

-- 中間テーブル（論文×タグ）
CREATE TABLE paper_tags (
  paper_id BIGINT NOT NULL,
  tag_id   BIGINT NOT NULL,
  PRIMARY KEY (paper_id, tag_id),
  CONSTRAINT fk_paper_tags_paper FOREIGN KEY (paper_id) REFERENCES papers(id) ON DELETE CASCADE,
  CONSTRAINT fk_paper_tags_tag   FOREIGN KEY (tag_id)   REFERENCES tags(id)   ON DELETE CASCADE
);
CREATE INDEX idx_paper_tags_tag    ON paper_tags(tag_id);
CREATE INDEX idx_paper_tags_paper  ON paper_tags(paper_id);
